USE SalesOrderDB;
GO

-- Check ALL columns in SalesOrder table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SalesOrder'
ORDER BY ORDINAL_POSITION;